name: Qwiet PreZero 2
on:
  push:
    branches: [ "master"]
    
jobs:
  Package:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
          java-version: '8'
          distribution: 'adopt'

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
          node-version: 16
          
    - name: Build with Yarn | NPM and Create WAR file
      run: |
        yarn config set legacy-peer-deps true
        yarn global add node-gyp
        yarn add node-sass --force
        yarn install --force
        npm run ng build --prod --aot && grunt

    - name: Upload WAR file as artifact
      uses: actions/upload-artifact@v2 
      with:
        name: Helpline1097-UI
        path: target/
    - name: Download ShiftLeft CLI
      run: |
        curl https://cdn.shiftleft.io/download/sl > ${GITHUB_WORKSPACE}/sl && chmod a+rx ${GITHUB_WORKSPACE}/sl
    # ShiftLeft requires Java 1.8. Post the package step override the version
    - name: Setup Java JDK
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 8
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: NextGen Static Analysis TS
      run: ${GITHUB_WORKSPACE}/sl analyze --strict --wait --app Helpline1097_UI_TSJS --tag app.group=AMRIT_HelpMCTS_UI --tag app.group=AMRIT_TSJS --tag app.group=AMRIT --tag branch=${{ github.head_ref || steps.extract_branch.outputs.branch }} --js --cpg . -- --ts
      env:
        SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
        SHIFTLEFT_API_HOST: www.shiftleft.io
        SHIFTLEFT_GRPC_TELEMETRY_HOST: telemetry.shiftleft.io:443
        SHIFTLEFT_GRPC_API_HOST: api.shiftleft.io:443
    - name: NextGen Static Analysis Java
      run: ${GITHUB_WORKSPACE}/sl analyze --strict --wait --app Helpline1097_UI_Java --tag app.group=AMRIT_HelpMCTS_UI --tag app.group=AMRIT --tag branch=${{ github.head_ref || steps.extract_branch.outputs.branch }} --tag app.group=AMRIT_Java --vcs-prefix-correction "*=src/main/java/" --oss-project-dir . --java target/Helpline1097-UI.war
      env:
        SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
        SHIFTLEFT_API_HOST: www.shiftleft.io
        SHIFTLEFT_GRPC_TELEMETRY_HOST: telemetry.shiftleft.io:443
        SHIFTLEFT_GRPC_API_HOST: api.shiftleft.io:443
